"""Actual map setup has been done here. map-engine"""

LEGEND = {}

{
    "satellite": {
        "type": "raster",
        "promoteId": "id",
        "tiles": ["https://api.maptiler.com/tiles/satellite-v2/{z}/{x}/{y}.jpg?key=GWZONJhjMFBnGpzoP3UY"],
    },
    "mv_grid_district_data": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/mv_grid_district_data_mvt/{z}/{x}/{y}/"],
    },
    "load_area": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/load_area_mvt/{z}/{x}/{y}/"],
    },
    "load_area_line": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/load_area_line_mvt/{z}/{x}/{y}/"],
    },
    "h2_voronoi": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/h2_voronoi_mvt/{z}/{x}/{y}/"],
    },
    "ch4_voronoi": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/ch4_voronoi_mvt/{z}/{x}/{y}/"],
    },
    "gas_potential_biogas_production_2035": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/gas_potential_biogas_production_2035_mvt/{z}/{x}/{y}/"],
    },
    "gas_potential_natural_gas_production_2035": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/gas_potential_natural_gas_production_2035_mvt/{z}/{x}/{y}/"],
    },
    "gas_methane_for_industry": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/gas_methane_for_industry_mvt/{z}/{x}/{y}/"],
    },
    "gas_hydrogen_for_industry": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/gas_hydrogen_for_industry_mvt/{z}/{x}/{y}/"],
    },
    "demand_transport_heavy_duty_transport_2035": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/demand_transport_heavy_duty_transport_2035_mvt/{z}/{x}/{y}/"],
    },
    "static": {"type": "vector", "promoteId": "id", "tiles": ["http://127.0.0.1:8000/map/static_mvt/{z}/{x}/{y}/"]},
    "flex_electricity_dynamic_line_rating_2035": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/flex_electricity_dynamic_line_rating_2035_mvt/{z}/{x}/{y}/"],
    },
    "potential_h2_underground_storage_2035": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/potential_h2_underground_storage_2035_mvt/{z}/{x}/{y}/"],
    },
    "potential_ch4_store_2035": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/potential_ch4_store_2035_mvt/{z}/{x}/{y}/"],
    },
    "heat_solarthermal_2035": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/heat_solarthermal_2035_mvt/{z}/{x}/{y}/"],
    },
    "heat_geothermal_2035": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/heat_geothermal_2035_mvt/{z}/{x}/{y}/"],
    },
    "central_heatpumps_2035": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/central_heatpumps_2035_mvt/{z}/{x}/{y}/"],
    },
    "heating_households_cts_2035": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/heating_households_cts_2035_mvt/{z}/{x}/{y}/"],
    },
    "country": {"type": "vector", "promoteId": "id", "tiles": ["http://127.0.0.1:8000/map/country_mvt/{z}/{x}/{y}/"]},
    "state": {"type": "vector", "promoteId": "id", "tiles": ["http://127.0.0.1:8000/map/state_mvt/{z}/{x}/{y}/"]},
    "district": {"type": "vector", "promoteId": "id", "tiles": ["http://127.0.0.1:8000/map/district_mvt/{z}/{x}/{y}/"]},
    "municipality": {
        "type": "vector",
        "promoteId": "id",
        "tiles": ["http://127.0.0.1:8000/map/municipality_mvt/{z}/{x}/{y}/"],
    },
    "wind_offshore_wind_parks_2035": {
        "type": "geojson",
        "promoteId": "id",
        "data": "http://127.0.0.1:8000/map/clusters/wind_offshore_wind_parks_2035.geojson",
        "cluster": True,
        "clusterMaxZoom": 11,
    },
    "wind_onshore_wind_parks_2035": {
        "type": "geojson",
        "promoteId": "id",
        "data": "http://127.0.0.1:8000/map/clusters/wind_onshore_wind_parks_2035.geojson",
        "cluster": True,
        "clusterMaxZoom": 11,
    },
    "ehv_hv_station": {
        "type": "geojson",
        "promoteId": "id",
        "data": "http://127.0.0.1:8000/map/clusters/ehv_hv_station.geojson",
        "cluster": True,
        "clusterMaxZoom": 11,
    },
    "hv_mv_station": {
        "type": "geojson",
        "promoteId": "id",
        "data": "http://127.0.0.1:8000/map/clusters/hv_mv_station.geojson",
        "cluster": True,
        "clusterMaxZoom": 11,
    },
    "pv_roof-top_pv_plants_2035": {
        "type": "geojson",
        "promoteId": "id",
        "data": "http://127.0.0.1:8000/map/clusters/pv_roof-top_pv_plants_2035.geojson",
        "cluster": True,
        "clusterMaxZoom": 11,
    },
    "pv_ground-mounted_pv_plants_2035": {
        "type": "geojson",
        "promoteId": "id",
        "data": "http://127.0.0.1:8000/map/clusters/pv_ground-mounted_pv_plants_2035.geojson",
        "cluster": True,
        "clusterMaxZoom": 11,
    },
}
[
    {
        "id": "mv_grid_district_data",
        "source": "mv_grid_district_data",
        "type": "fill",
        "paint": {"fill-color": "#ffffff", "fill-opacity": 0.3, "fill-outline-color": "rgba(115,62,136,0.2)"},
        "source-layer": "mv_grid_district_data",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "mv_grid_district_data_line",
        "source": "mv_grid_district_data",
        "type": "line",
        "paint": {"line-color": "rgba(115,62,136,0.2)", "line-width": 0.8},
        "source-layer": "mv_grid_district_data_line",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "load_area",
        "source": "load_area",
        "type": "fill",
        "paint": {"fill-color": "#ffffff", "fill-opacity": 0.6},
        "source-layer": "load_area",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "load_area_line",
        "source": "load_area_line",
        "type": "line",
        "paint": {"line-color": "rgb(115,62,136)", "line-width": 0.8},
        "source-layer": "load_area_line",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "h2_voronoi",
        "source": "h2_voronoi",
        "type": "fill",
        "paint": {"fill-color": "#ffffff", "fill-opacity": 0.3, "fill-outline-color": "rgba(115,62,136,0.2)"},
        "source-layer": "h2_voronoi",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "h2_voronoi_line",
        "source": "h2_voronoi",
        "type": "line",
        "paint": {"line-color": "rgba(115,62,136,0.2)", "line-width": 0.8},
        "source-layer": "h2_voronoi_line",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "ch4_voronoi",
        "source": "ch4_voronoi",
        "type": "fill",
        "paint": {"fill-color": "#ffffff", "fill-opacity": 0.3, "fill-outline-color": "rgba(115,62,136,0.2)"},
        "source-layer": "ch4_voronoi",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "ch4_voronoi_line",
        "source": "ch4_voronoi",
        "type": "line",
        "paint": {"line-color": "rgba(115,62,136,0.2)", "line-width": 0.8},
        "source-layer": "ch4_voronoi_line",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "gas_potential_biogas_production_2035",
        "source": "gas_potential_biogas_production_2035",
        "type": "fill",
        "paint": {"fill-color": "#52C41A", "fill-opacity": 0.8},
        "source-layer": "gas_potential_biogas_production_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "gas_potential_natural_gas_production_2035",
        "source": "gas_potential_natural_gas_production_2035",
        "type": "fill",
        "paint": {"fill-color": "grey", "fill-opacity": 0.8},
        "source-layer": "gas_potential_natural_gas_production_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "gas_methane_for_industry",
        "source": "gas_methane_for_industry",
        "type": "fill",
        "paint": {"fill-color": "#ffffff", "fill-opacity": 0.3, "fill-outline-color": "rgba(115,62,136,0.2)"},
        "source-layer": "gas_methane_for_industry",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "gas_hydrogen_for_industry",
        "source": "gas_hydrogen_for_industry",
        "type": "fill",
        "paint": {"fill-color": "#ffffff", "fill-opacity": 0.3, "fill-outline-color": "rgba(115,62,136,0.2)"},
        "source-layer": "gas_hydrogen_for_industry",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "demand_transport_heavy_duty_transport_2035",
        "source": "demand_transport_heavy_duty_transport_2035",
        "type": "fill",
        "paint": {"fill-color": "grey", "fill-opacity": 0.8},
        "source-layer": "demand_transport_heavy_duty_transport_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "wind_onshore_potential_areas_2035",
        "source": "static",
        "type": "fill",
        "paint": {"fill-color": "darkblue", "fill-opacity": 0.8},
        "source-layer": "wind_onshore_potential_areas_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "pv_ground-mounted_potential_areas_agriculture_2035",
        "source": "static",
        "type": "fill",
        "paint": {"fill-color": "gold", "fill-opacity": 0.8},
        "source-layer": "pv_ground-mounted_potential_areas_agriculture_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "pv_ground-mounted_potential_areas_highways_railroad_2035",
        "source": "static",
        "type": "fill",
        "paint": {"fill-color": "gold", "fill-opacity": 0.8},
        "source-layer": "pv_ground-mounted_potential_areas_highways_railroad_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "ehv_line",
        "source": "static",
        "type": "line",
        "paint": {"line-color": "blue"},
        "source-layer": "ehv_line",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "hv_line",
        "source": "static",
        "type": "line",
        "paint": {"line-color": "darkblue"},
        "source-layer": "hv_line",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "methan_grid_line_2035",
        "source": "static",
        "type": "line",
        "paint": {"line-color": "darkblue"},
        "source-layer": "methan_grid_line_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "flex_electricity_dynamic_line_rating_2035",
        "source": "flex_electricity_dynamic_line_rating_2035",
        "type": "line",
        "paint": {"line-color": ["case", ["==", ["get", "dlr"], 1], "red", "black"], "line-width": 1},
        "source-layer": "flex_electricity_dynamic_line_rating_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "potential_h2_underground_storage_2035",
        "source": "potential_h2_underground_storage_2035",
        "type": "fill",
        "paint": {"fill-color": "#52C41A", "fill-opacity": 0.8},
        "source-layer": "potential_h2_underground_storage_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "potential_ch4_store_2035",
        "source": "potential_ch4_store_2035",
        "type": "fill",
        "paint": {"fill-color": "#52C41A", "fill-opacity": 0.8},
        "source-layer": "potential_ch4_store_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "heat_solarthermal_2035",
        "source": "heat_solarthermal_2035",
        "type": "fill",
        "paint": {"fill-color": "#52C41A", "fill-opacity": 0.8},
        "source-layer": "heat_solarthermal_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "heat_geothermal_2035",
        "source": "heat_geothermal_2035",
        "type": "fill",
        "paint": {"fill-color": "#52C41A", "fill-opacity": 0.8},
        "source-layer": "heat_geothermal_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "central_heatpumps_2035",
        "source": "central_heatpumps_2035",
        "type": "fill",
        "paint": {"fill-color": "#52C41A", "fill-opacity": 0.8},
        "source-layer": "central_heatpumps_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "heating_households_cts_2035",
        "source": "heating_households_cts_2035",
        "type": "fill",
        "paint": {"fill-color": "#52C41A", "fill-opacity": 0.8},
        "source-layer": "heating_households_cts_2035",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "country",
        "source": "country",
        "type": "line",
        "paint": {"line-color": "rgb(115,62,136)", "line-width": 0.8},
        "source-layer": "country",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "countrylabel",
        "source": "country",
        "type": "symbol",
        "layout": {
            "text-variable-anchor": ["center", "top"],
            "icon-allow-overlap": True,
            "text-radial-offset": 2,
            "text-field": "{name}",
            "text-font": ["Flexo Medium"],
            "text-letter-spacing": 0.04,
        },
        "source-layer": "countrylabel",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "state",
        "source": "state",
        "type": "line",
        "paint": {
            "line-color": "rgb(115,62,136)",
            "line-width": ["case", ["boolean", ["feature-state", "hover"], False], 3, 0.25],
        },
        "source-layer": "state",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "statelabel",
        "source": "state",
        "type": "symbol",
        "layout": {
            "text-variable-anchor": ["center", "top"],
            "icon-allow-overlap": True,
            "text-radial-offset": 2,
            "text-field": "{name}",
            "text-font": ["Flexo Medium"],
            "text-letter-spacing": 0.04,
        },
        "paint": {
            "text-color": ["case", ["boolean", ["feature-state", "hover"], False], "#222222", "#000000"],
            "text-halo-color": "hsl(0, 0%, 100%)",
            "text-halo-width": 0.85,
            "text-halo-blur": 1.5,
        },
        "source-layer": "statelabel",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "district",
        "source": "district",
        "type": "line",
        "paint": {
            "line-color": "rgb(115,62,136)",
            "line-width": ["case", ["boolean", ["feature-state", "hover"], False], 3, 0.25],
        },
        "source-layer": "district",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "districtlabel",
        "source": "district",
        "type": "symbol",
        "layout": {
            "text-variable-anchor": ["center", "top"],
            "icon-allow-overlap": True,
            "text-radial-offset": 2,
            "text-field": "{name}",
            "text-size": {"stops": [[0, 0], [7, 0], [8, 12], [10, 14]]},
            "text-font": ["Flexo Medium"],
            "text-letter-spacing": 0.04,
        },
        "paint": {
            "text-color": ["case", ["boolean", ["feature-state", "hover"], False], "#222222", "#000000"],
            "text-halo-color": "hsl(0, 0%, 100%)",
            "text-halo-width": 0.85,
            "text-halo-blur": 1.5,
        },
        "source-layer": "districtlabel",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "municipality",
        "source": "municipality",
        "type": "line",
        "paint": {
            "line-color": "rgb(115,62,136)",
            "line-width": ["case", ["boolean", ["feature-state", "hover"], False], 3, 0.25],
        },
        "source-layer": "municipality",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "municipalitylabel",
        "source": "municipality",
        "type": "symbol",
        "layout": {
            "text-variable-anchor": ["center", "top"],
            "icon-allow-overlap": True,
            "text-radial-offset": 2,
            "text-field": "{name}",
            "text-size": {"stops": [[0, 0], [9, 0], [11, 14]]},
            "text-font": ["Flexo Medium"],
            "text-letter-spacing": 0.04,
        },
        "paint": {
            "text-color": ["case", ["boolean", ["feature-state", "hover"], False], "#222222", "#000000"],
            "text-halo-color": "hsl(0, 0%, 100%)",
            "text-halo-width": 0.85,
            "text-halo-blur": 1.5,
        },
        "source-layer": "municipalitylabel",
        "minzoom": 2,
        "maxzoom": 22,
    },
    {
        "id": "wind_offshore_wind_parks_2035",
        "source": "wind_offshore_wind_parks_2035",
        "type": "symbol",
        "filter": ["!", ["has", "point_count"]],
        "layout": {"icon-image": "wind", "icon-size": 0.8, "icon-allow-overlap": False},
        "paint": {"icon-color": "blue"},
    },
    {
        "id": "wind_offshore_wind_parks_2035_cluster",
        "source": "wind_offshore_wind_parks_2035",
        "type": "circle",
        "filter": ["has", "point_count"],
        "paint": {"circle-color": "#6A89CC", "circle-radius": ["step", ["get", "point_count"], 15, 125, 20, 950, 25]},
    },
    {
        "id": "wind_offshore_wind_parks_2035_cluster_count",
        "source": "wind_offshore_wind_parks_2035",
        "type": "symbol",
        "filter": ["has", "point_count"],
        "layout": {
            "text-field": "{point_count_abbreviated}",
            "text-font": ["DIN Offc Pro Medium", "Arial Unicode MS Bold"],
            "text-size": 12,
        },
    },
    {
        "id": "wind_onshore_wind_parks_2035",
        "source": "wind_onshore_wind_parks_2035",
        "type": "symbol",
        "filter": ["!", ["has", "point_count"]],
        "layout": {"icon-image": "wind", "icon-size": 0.8, "icon-allow-overlap": False},
        "paint": {"icon-color": "blue"},
    },
    {
        "id": "wind_onshore_wind_parks_2035_cluster",
        "source": "wind_onshore_wind_parks_2035",
        "type": "circle",
        "filter": ["has", "point_count"],
        "paint": {"circle-color": "#6A89CC", "circle-radius": ["step", ["get", "point_count"], 15, 125, 20, 950, 25]},
    },
    {
        "id": "wind_onshore_wind_parks_2035_cluster_count",
        "source": "wind_onshore_wind_parks_2035",
        "type": "symbol",
        "filter": ["has", "point_count"],
        "layout": {
            "text-field": "{point_count_abbreviated}",
            "text-font": ["DIN Offc Pro Medium", "Arial Unicode MS Bold"],
            "text-size": 12,
        },
    },
    {
        "id": "ehv_hv_station",
        "source": "ehv_hv_station",
        "type": "symbol",
        "filter": ["!", ["has", "point_count"]],
        "layout": {"icon-image": "station", "icon-size": 0.5, "icon-allow-overlap": True},
    },
    {
        "id": "ehv_hv_station_cluster",
        "source": "ehv_hv_station",
        "type": "circle",
        "filter": ["has", "point_count"],
        "paint": {
            "circle-color": ["step", ["get", "point_count"], "#51bbd6", 100, "#f1f075", 750, "#f28cb1"],
            "circle-radius": ["step", ["get", "point_count"], 20, 100, 30, 750, 40],
        },
    },
    {
        "id": "ehv_hv_station_cluster_count",
        "source": "ehv_hv_station",
        "type": "symbol",
        "filter": ["has", "point_count"],
        "layout": {
            "text-field": "{point_count_abbreviated}",
            "text-font": ["DIN Offc Pro Medium", "Arial Unicode MS Bold"],
            "text-size": 12,
        },
    },
    {
        "id": "hv_mv_station",
        "source": "hv_mv_station",
        "type": "symbol",
        "filter": ["!", ["has", "point_count"]],
        "layout": {"icon-image": "station", "icon-size": 0.8, "icon-allow-overlap": True},
    },
    {
        "id": "hv_mv_station_cluster",
        "source": "hv_mv_station",
        "type": "circle",
        "filter": ["has", "point_count"],
        "paint": {
            "circle-color": ["step", ["get", "point_count"], "#51bbd6", 100, "#f1f075", 750, "#f28cb1"],
            "circle-radius": ["step", ["get", "point_count"], 20, 100, 30, 750, 40],
        },
    },
    {
        "id": "hv_mv_station_cluster_count",
        "source": "hv_mv_station",
        "type": "symbol",
        "filter": ["has", "point_count"],
        "layout": {
            "text-field": "{point_count_abbreviated}",
            "text-font": ["DIN Offc Pro Medium", "Arial Unicode MS Bold"],
            "text-size": 12,
        },
    },
    {
        "id": "pv_roof-top_pv_plants_2035",
        "source": "pv_roof-top_pv_plants_2035",
        "type": "symbol",
        "filter": ["!", ["has", "point_count"]],
        "layout": {"icon-image": "solar", "icon-size": 0.8, "icon-allow-overlap": True},
        "paint": {"icon-color": "yellow", "icon-halo-color": "red"},
    },
    {
        "id": "pv_roof-top_pv_plants_2035_cluster",
        "source": "pv_roof-top_pv_plants_2035",
        "type": "circle",
        "filter": ["has", "point_count"],
        "paint": {"circle-color": "#FFD660", "circle-radius": 20},
    },
    {
        "id": "pv_roof-top_pv_plants_2035_cluster_count",
        "source": "pv_roof-top_pv_plants_2035",
        "type": "symbol",
        "filter": ["has", "point_count"],
        "layout": {
            "text-field": "{point_count_abbreviated}",
            "text-font": ["DIN Offc Pro Medium", "Arial Unicode MS Bold"],
            "text-size": 12,
        },
    },
    {
        "id": "pv_ground-mounted_pv_plants_2035",
        "source": "pv_ground-mounted_pv_plants_2035",
        "type": "symbol",
        "filter": ["!", ["has", "point_count"]],
        "layout": {"icon-image": "solar", "icon-size": 0.8, "icon-allow-overlap": True},
        "paint": {"icon-color": "yellow"},
    },
    {
        "id": "pv_ground-mounted_pv_plants_2035_cluster",
        "source": "pv_ground-mounted_pv_plants_2035",
        "type": "circle",
        "filter": ["has", "point_count"],
        "paint": {"circle-color": "#F6B93B", "circle-radius": ["step", ["get", "point_count"], 15, 125, 20, 950, 25]},
    },
    {
        "id": "pv_ground-mounted_pv_plants_2035_cluster_count",
        "source": "pv_ground-mounted_pv_plants_2035",
        "type": "symbol",
        "filter": ["has", "point_count"],
        "layout": {
            "text-field": "{point_count_abbreviated}",
            "text-font": ["DIN Offc Pro Medium", "Arial Unicode MS Bold"],
            "text-size": 12,
        },
    },
]
[]
