# Generated by Django 3.2.3 on 2021-09-06 12:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_type', models.CharField(choices=[('country', 'Land'), ('state', 'Bundesland'), ('district', 'Kreis'), ('municipality', 'Gemeinde')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('region', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.region')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('region', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.region')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('region', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.region')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('region', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.region')),
            ],
        ),
    ]
