# Generated by Django 3.2.3 on 2021-09-08 15:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_demandcts_demandhousehold_demandmodel_ehvhvsubstation_ehvline_hvline_hvmvsubstation_mvgriddistricts_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvgriddistricts',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
