# Generated by Django 3.2.18 on 2023-04-12 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_region_layer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandHeatingHhCts',
            fields=[
                ('demandmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.demandmodel')),
            ],
            bases=('map.demandmodel',),
        ),
    ]
