# Generated by Django 3.2.18 on 2023-04-18 07:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_delete_multi_table_inheritance_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandCts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('demand', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Demand CTS',
                'verbose_name_plural': 'Demands CTS',
            },
        ),
        migrations.CreateModel(
            name='DemandHeatingHhCts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('demand', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Demand Heating Household and CTS',
                'verbose_name_plural': 'Demand Heating Household and CTS',
            },
        ),
        migrations.CreateModel(
            name='DemandHousehold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('demand', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Demand Household',
                'verbose_name_plural': 'Demands Household',
            },
        ),
    ]
