# Generated by Django 3.2.18 on 2023-04-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_mvgriddistricts_bus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvgriddistricts',
            name='bus_id',
            field=models.IntegerField(null=True),
        ),
    ]
