# Generated by Django 3.2.18 on 2023-04-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_alter_mvgriddistricts_bus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportMitDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.IntegerField()),
                ('mv_grid_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.mvgriddistricts')),
            ],
        ),
    ]
