# Generated by Django 3.2.18 on 2023-04-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_transportmitdemand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mvgriddistricts',
            name='bus_id',
        ),
        migrations.RemoveField(
            model_name='transportmitdemand',
            name='demand',
        ),
        migrations.AddField(
            model_name='transportmitdemand',
            name='annual_demand',
            field=models.FloatField(default=None, verbose_name='Annual Demand (in MWh)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportmitdemand',
            name='max',
            field=models.FloatField(default=None, verbose_name='Maximal value (in MWh)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportmitdemand',
            name='min',
            field=models.FloatField(default=None, verbose_name='Minimal value (in MWh)'),
            preserve_default=False,
        ),
    ]
