# Generated by Django 3.2.18 on 2023-05-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20230427_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportmitdemand',
            options={'verbose_name': 'Transport MIT Demand', 'verbose_name_plural': 'Transport MIT Demands'},
        ),
        migrations.RemoveField(
            model_name='demandhousehold',
            name='demand',
        ),
        migrations.RemoveField(
            model_name='demandhousehold',
            name='geom',
        ),
        migrations.AddField(
            model_name='demandhousehold',
            name='max',
            field=models.FloatField(default=None, verbose_name='Maximal value (in MWh)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandhousehold',
            name='min',
            field=models.FloatField(default=None, verbose_name='Minimal value (in MWh)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandhousehold',
            name='mv_grid_district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='map.mvgriddistricts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandhousehold',
            name='sum',
            field=models.FloatField(default=None, verbose_name='Sum (in MWh)'),
            preserve_default=False,
        ),
    ]
