# Generated by Django 3.2.18 on 2023-05-15 13:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_maplayer_mvgriddistrictdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maplayer',
            old_name='color_palette',
            new_name='geom_layer',
        ),
        migrations.RenameField(
            model_name='maplayer',
            old_name='layer_identifier',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='maplayer',
            old_name='layer_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='display_category',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='num_colors',
        ),
        migrations.AddField(
            model_name='maplayer',
            name='category',
            field=models.CharField(choices=[('demand', 'Demand'), ('supply', 'Supply'), ('grids', 'Grids'), ('model', 'Data Model')], default='demand', max_length=16),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='layer_style',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='choropleth_field',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='popup_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='popup_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='popup_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
