# Generated by Django 3.2.18 on 2023-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_auto_20230515_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='layer_style',
        ),
        migrations.AddField(
            model_name='maplayer',
            name='choropleth_color_palette',
            field=models.CharField(default='YlGnBu', max_length=64),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='choropleth_num_colors',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
    ]
