# Generated by Django 3.2.18 on 2023-05-17 13:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_maplayer_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='choropleth_color_palette',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='choropleth_num_colors',
        ),
        migrations.AddField(
            model_name='maplayer',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
    ]
