# Generated by Django 3.2.18 on 2023-05-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_maplayer_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='scenario',
            field=models.CharField(choices=[('2035', '2035'), ('100RE', '100RE'), ('both', 'both')], default='2035', max_length=5),
        ),
    ]
