# Generated by Django 3.2.18 on 2023-05-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0027_h2voronoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='demand_transport_mit_demand_100re_annual_demand',
            field=models.FloatField(null=True, verbose_name='Annual Demand (MWh)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='demand_transport_mit_demand_100re_max',
            field=models.FloatField(null=True, verbose_name='Maximal hourly demand (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='demand_transport_mit_demand_100re_min',
            field=models.FloatField(null=True, verbose_name='Minimal hourly demand (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='demand_transport_mit_demand_2035_annual_demand',
            field=models.FloatField(null=True, verbose_name='Annual Demand (MWh)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='demand_transport_mit_demand_2035_max',
            field=models.FloatField(null=True, verbose_name='Maximal hourly demand (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='demand_transport_mit_demand_2035_min',
            field=models.FloatField(null=True, verbose_name='Minimal hourly demand (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='flex_pot_electricity_electromobility_100re_charging_demand',
            field=models.FloatField(null=True, verbose_name='Charging demand (MWh)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='flex_pot_electricity_electromobility_100re_flex_demand',
            field=models.FloatField(null=True, verbose_name='Flexible demand (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='flex_pot_electricity_electromobility_100re_flex_share',
            field=models.FloatField(null=True, verbose_name='Share of flexible demand (%)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='flex_pot_electricity_electromobility_2035_charging_demand',
            field=models.FloatField(null=True, verbose_name='Charging demand (MWh)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='flex_pot_electricity_electromobility_2035_flex_demand',
            field=models.FloatField(null=True, verbose_name='Flexible demand (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='flex_pot_electricity_electromobility_2035_flex_share',
            field=models.FloatField(null=True, verbose_name='hare of flexible demand (%)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_other_biomass_fired_power_plants_2035_el_capacity',
            field=models.FloatField(null=True, verbose_name='Installed capacity (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_other_biomass_fired_power_plants_2035_unit_count',
            field=models.FloatField(null=True, verbose_name='Number of power plants'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_other_gas_fired_power_plants_2035_el_capacity',
            field=models.FloatField(null=True, verbose_name='Installed capacity (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_other_gas_fired_power_plants_2035_unit_count',
            field=models.FloatField(null=True, verbose_name='Number of power plants'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_other_hydro_2035_el_capacity',
            field=models.FloatField(null=True, verbose_name='Installed capacity (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_other_hydro_2035_unit_count',
            field=models.FloatField(null=True, verbose_name='Number of power plants'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_other_other_power_plants_2035_el_capacity',
            field=models.FloatField(null=True, verbose_name='Installed capacity (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_other_other_power_plants_2035_unit_count',
            field=models.FloatField(null=True, verbose_name='Number of power plants'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_pv_roof_top_installed_capacity_100re_el_capacity',
            field=models.FloatField(null=True, verbose_name='Installed capacity (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_pv_roof_top_installed_capacity_100re_unit_count',
            field=models.FloatField(null=True, verbose_name='Number of power plants'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_pv_roof_top_installed_capacity_2035_el_capacity',
            field=models.FloatField(null=True, verbose_name='Installed capacity (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_pv_roof_top_installed_capacity_2035_unit_count',
            field=models.FloatField(null=True, verbose_name='Number of power plants'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_pv_roof_top_potential_production_100re_feedin',
            field=models.FloatField(null=True, verbose_name='Potential production feedin'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_pv_roof_top_potential_production_2035_feedin',
            field=models.FloatField(null=True, verbose_name='Potential production feedin'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_wind_onshore_installed_capacity_100re_el_capacity',
            field=models.FloatField(null=True, verbose_name='Installed capacity (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_wind_onshore_installed_capacity_100re_unit_count',
            field=models.FloatField(null=True, verbose_name='Number of power plants'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_wind_onshore_installed_capacity_2035_el_capacity',
            field=models.FloatField(null=True, verbose_name='Installed capacity (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_wind_onshore_installed_capacity_2035_unit_count',
            field=models.FloatField(null=True, verbose_name='Number of power plants'),
        ),
    ]
