# Generated by Django 3.2.18 on 2023-05-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_auto_20230525_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='data_model',
            field=models.CharField(default='MVGridDistrictData', help_text='The name of the model that holds the data.', max_length=64),
            preserve_default=False,
        ),
    ]
