# Generated by Django 3.2.18 on 2023-05-29 19:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0029_maplayer_data_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPotElDynamicLineRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('el_peakload', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MethaneGridLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PotentialH2UndergroundStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('e_nom_max', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SupplyBiomass',
        ),
        migrations.DeleteModel(
            name='SupplyRunOfRiver',
        ),
        migrations.AlterField(
            model_name='gaspotentialnaturalgasproduction',
            name='p_nom',
            field=models.FloatField(null=True, verbose_name='P nom (MWh)'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='description',
            field=models.CharField(blank=True, help_text='The description that can be found in the frontend, when clicking on the info-icon.', max_length=1024, null=True),
        ),
    ]
