# Generated by Django 3.2.18 on 2023-05-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0030_auto_20230529_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='choropleth_unit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
