# Generated by Django 3.2.18 on 2023-05-30 12:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0031_maplayer_choropleth_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralHeatPumps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('capacity', models.FloatField(null=True, verbose_name='Electrical capacity (MW))')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeatGeothermal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('capacity', models.FloatField(null=True, verbose_name='Electrical capacity (MW))')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeatingHouseholdsCts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('annual_demand', models.FloatField(null=True)),
                ('max', models.FloatField(verbose_name='Maximal demand (MW)')),
                ('min', models.FloatField(verbose_name='Minimal demand (MW)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeatSolarthermal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('capacity', models.FloatField(null=True, verbose_name='Electrical capacity (MW))')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PotentialCH4Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('e_nom', models.FloatField(null=True, verbose_name='Storage Capacity (MWh)')),
            ],
        ),
        migrations.AlterField(
            model_name='potentialh2undergroundstorage',
            name='e_nom_max',
            field=models.FloatField(null=True, verbose_name='Storage Capacity (MWh)'),
        ),
    ]
