# Generated by Django 3.2.18 on 2023-05-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0033_auto_20230530_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='demand_electricity_households_100re_max',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='demand_electricity_households_100re_min',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='demand_electricity_households_100re_sum',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='demand_transport_mit_demand_100re_annual_demand',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='demand_transport_mit_demand_100re_max',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='demand_transport_mit_demand_100re_min',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='flex_pot_electricity_electromobility_100re_charging_demand',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='flex_pot_electricity_electromobility_100re_flex_demand',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='flex_pot_electricity_electromobility_100re_flex_share',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='supply_pv_ground_mounted_installed_capacity_100re_el_capacity',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='supply_pv_ground_mounted_installed_capacity_100re_unit_count',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='supply_pv_roof_top_installed_capacity_100re_el_capacity',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='supply_pv_roof_top_installed_capacity_100re_unit_count',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='supply_pv_roof_top_potential_production_100re_feedin',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='supply_pv_roof_top_potential_production_2035_feedin',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='supply_wind_onshore_installed_capacity_100re_el_capacity',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='supply_wind_onshore_installed_capacity_100re_unit_count',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='transport_mit_number_of_evs_100re_bev_luxury',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='transport_mit_number_of_evs_100re_bev_medium',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='transport_mit_number_of_evs_100re_bev_mini',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='transport_mit_number_of_evs_100re_ev_count',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='transport_mit_number_of_evs_100re_phev_luxury',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='transport_mit_number_of_evs_100re_phev_medium',
        ),
        migrations.RemoveField(
            model_name='mvgriddistrictdata',
            name='transport_mit_number_of_evs_100re_phev_mini',
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='demand_electricity_cts_2035_max',
            field=models.FloatField(null=True, verbose_name='Maximal hourly demand (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='demand_electricity_cts_2035_min',
            field=models.FloatField(null=True, verbose_name='Minimal hourly demand (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='demand_electricity_cts_2035_sum',
            field=models.FloatField(null=True, verbose_name='Annual Demand (MWh)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='demand_electricity_industry_2035_max',
            field=models.FloatField(null=True, verbose_name='Maximal hourly demand (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='demand_electricity_industry_2035_min',
            field=models.FloatField(null=True, verbose_name='Minimal hourly demand (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='demand_electricity_industry_2035_sum',
            field=models.FloatField(null=True, verbose_name='Annual Demand (MWh)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='demand_heat_individual_heating_households_and_cts_2035_max',
            field=models.FloatField(null=True, verbose_name='Maximal hourly demand (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='demand_heat_individual_heating_households_and_cts_2035_min',
            field=models.FloatField(null=True, verbose_name='Minimal hourly demand (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='demand_heat_individual_heating_households_and_cts_2035_sum',
            field=models.FloatField(null=True, verbose_name='Annual Demand (MWh)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='flexibility_potential_electricity_dsm_2035_dsm_potential',
            field=models.FloatField(null=True, verbose_name='Demand Side Potential (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='flexibility_potential_storage_home_storage_2035_el_capacity',
            field=models.FloatField(null=True, verbose_name='Installed capacity (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='flexibility_potential_storage_home_storage_2035_unit_count',
            field=models.FloatField(null=True, verbose_name='Number of power plants'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='flexibility_potential_storage_pumped_storage_2035_el_capacity',
            field=models.FloatField(null=True, verbose_name='Installed capacity (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='flexibility_potential_storage_pumped_storage_2035_unit_count',
            field=models.FloatField(null=True, verbose_name='Number of power plants'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='supply_heat_individual_heat_pumps_2035_capacity',
            field=models.FloatField(null=True, verbose_name='Installed capacity (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='supply_pv_ground_mounted_potential_electricity_production_2035_feedin',
            field=models.FloatField(null=True, verbose_name='Potential el. prodcution feed-in (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='supply_pv_roof_top_potential_electricity_production_2035_feedin',
            field=models.FloatField(null=True, verbose_name='Potential el. prodcution feed-in (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='supply_wind_offshore_installed_capacity_2035_el_capacity',
            field=models.FloatField(null=True, verbose_name='Installed capacity (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='supply_wind_offshore_installed_capacity_2035_unit_count',
            field=models.FloatField(null=True, verbose_name='Number of power plants'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='supply_wind_offshore_potential_electricity_production_2035_feedin',
            field=models.FloatField(null=True, verbose_name='Potential el. prodcution feed-in (MW)'),
        ),
        migrations.AddField(
            model_name='mvgriddistrictdata',
            name='supply_wind_onshore_potential_electricity_production_2035_feedin',
            field=models.FloatField(null=True, verbose_name='Potential el. prodcution feed-in (MW)'),
        ),
        migrations.AlterField(
            model_name='mvgriddistrictdata',
            name='supply_pv_roof_top_installed_capacity_2035_unit_count',
            field=models.IntegerField(null=True, verbose_name='Number of power plants'),
        ),
    ]
