# Generated by Django 3.2.18 on 2023-05-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0035_auto_20230530_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mvgriddistrictdata',
            old_name='transport_mit_number_of_evs_2035_bev_luxury',
            new_name='demand_transport_mit_number_of_evs_2035_bev_luxury',
        ),
        migrations.RenameField(
            model_name='mvgriddistrictdata',
            old_name='transport_mit_number_of_evs_2035_bev_medium',
            new_name='demand_transport_mit_number_of_evs_2035_bev_medium',
        ),
        migrations.RenameField(
            model_name='mvgriddistrictdata',
            old_name='transport_mit_number_of_evs_2035_bev_mini',
            new_name='demand_transport_mit_number_of_evs_2035_bev_mini',
        ),
        migrations.RenameField(
            model_name='mvgriddistrictdata',
            old_name='transport_mit_number_of_evs_2035_ev_count',
            new_name='demand_transport_mit_number_of_evs_2035_ev_count',
        ),
        migrations.RenameField(
            model_name='mvgriddistrictdata',
            old_name='transport_mit_number_of_evs_2035_phev_luxury',
            new_name='demand_transport_mit_number_of_evs_2035_phev_luxury',
        ),
        migrations.RenameField(
            model_name='mvgriddistrictdata',
            old_name='transport_mit_number_of_evs_2035_phev_medium',
            new_name='demand_transport_mit_number_of_evs_2035_phev_medium',
        ),
        migrations.RenameField(
            model_name='mvgriddistrictdata',
            old_name='transport_mit_number_of_evs_2035_phev_mini',
            new_name='demand_transport_mit_number_of_evs_2035_phev_mini',
        ),
    ]
