# Generated by Django 3.2.18 on 2023-06-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0037_auto_20230601_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpoteldynamiclinerating',
            name='dlr',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
