# Generated by Django 3.2.18 on 2023-06-01 18:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0038_flexpoteldynamiclinerating_dlr'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='flexpoteldynamiclinerating',
            managers=[
                ('vector_tiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='gasch4industry',
            name='annual_demand',
            field=models.FloatField(null=True, verbose_name='Annual demand (MWh)'),
        ),
        migrations.AlterField(
            model_name='gash2industry',
            name='annual_demand',
            field=models.FloatField(null=True, verbose_name='Annual demand (MWh)'),
        ),
        migrations.AlterField(
            model_name='heatinghouseholdscts',
            name='annual_demand',
            field=models.FloatField(null=True, verbose_name='Annual demand (MWh)'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='category',
            field=models.CharField(choices=[('demand', 'Demand'), ('supply', 'Supply'), ('grids', 'Grids'), ('flexibility', 'Flexibility')], default='demand', help_text='The main category in the left panel in the frontend.', max_length=16),
        ),
        migrations.AlterField(
            model_name='transportheavyduty',
            name='annual_demand',
            field=models.FloatField(null=True, verbose_name='Annual demand (MWh)'),
        ),
    ]
