# Generated by Django 3.2.18 on 2023-06-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0039_auto_20230601_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='order_priority',
            field=models.PositiveSmallIntegerField(blank=True, help_text="The MapLayers in the frontend-panel on the left are ordered by their category, then sub-category and finally by this field. '1' is the highest priority.", null=True, verbose_name='Order priority Frontend'),
        ),
    ]
