# Generated by Django 3.2.18 on 2023-06-29 09:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0040_maplayer_order_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadArea100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('el_peakload', models.FloatField(null=True, verbose_name='Max. demand (MW)')),
                ('el_consumption', models.FloatField(null=True, verbose_name='Annual demand (MWh)')),
            ],
        ),
    ]
