# Generated by Django 3.2.18 on 2023-06-29 09:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0041_loadarea100re'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasCH4Industry100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('annual_demand', models.FloatField(null=True, verbose_name='Annual demand (MWh)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GasH2Industry100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('annual_demand', models.FloatField(null=True, verbose_name='Annual demand (MWh)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeatingHouseholdsCts100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('annual_demand', models.FloatField(null=True, verbose_name='Annual demand (MWh)')),
                ('max', models.FloatField(null=True, verbose_name='Maximal demand (MW)')),
                ('min', models.FloatField(null=True, verbose_name='Minimal demand (MW)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransportHeavyDuty100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('annual_demand', models.FloatField(null=True, verbose_name='Annual demand (MWh)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
