# Generated by Django 3.2.18 on 2023-06-29 09:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0042_gasch4industry100re_gash2industry100re_heatinghouseholdscts100re_transportheavyduty100re'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralHeatPumps100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('capacity', models.FloatField(null=True, verbose_name='Electrical capacity (MW))')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GasPotentialBiogasProduction100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('p_nom', models.FloatField(null=True, verbose_name='P nom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GasPotentialNaturalGasProduction100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('p_nom', models.FloatField(null=True, verbose_name='P nom (MWh)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeatGeothermal100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('capacity', models.FloatField(null=True, verbose_name='Electrical capacity (MW))')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeatSolarthermal100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('capacity', models.FloatField(null=True, verbose_name='Electrical capacity (MW))')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PVGroundMountedPotentialAreaAgriculture100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area_km2', models.FloatField(null=True, verbose_name='Potential area (km²)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PVGroundMountedPotentialAreaHighways_Railroads100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area_km2', models.FloatField(null=True, verbose_name='Potential area (km²)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WindOnshorePotentialArea100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area_km2', models.FloatField(null=True, verbose_name='Potential area (km²)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
