# Generated by Django 3.2.18 on 2023-06-29 09:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0043_centralheatpumps100re_gaspotentialbiogasproduction100re_gaspotentialnaturalgasproduction100re_heatge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVGroundMountedPVPlant100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('el_capacity', models.FloatField(verbose_name='Electrical Capacity')),
                ('voltage_level', models.PositiveIntegerField(verbose_name='Voltage level')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PVRoofTopPVPlant100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('el_capacity', models.FloatField(verbose_name='Electrical Capacity')),
                ('voltage_level', models.PositiveIntegerField(verbose_name='Voltage level')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WindOffshoreWindPark100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('el_capacity', models.FloatField(verbose_name='Electrical Capacity')),
                ('voltage_level', models.PositiveIntegerField(verbose_name='Voltage level')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WindOnshoreWindPark100RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('el_capacity', models.FloatField(verbose_name='Electrical Capacity')),
                ('voltage_level', models.PositiveIntegerField(verbose_name='Voltage level')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
