# Generated by Django 3.2.18 on 2023-06-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0045_mvgriddistrictdata100re'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mvgriddistrictdata100re',
            old_name='supply_pv_roof_top_potential_electricity_production_100re_feedin',
            new_name='supply_pv_roof_top_potential_electricity_production_feedin',
        ),
    ]
