# Generated by Django 3.2.18 on 2023-07-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0049_auto_20230719_0536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GasPotentialNaturalGasProduction100RE',
        ),
    ]
