# Generated by Django 3.2.18 on 2023-07-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0050_delete_gaspotentialnaturalgasproduction100re'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ch4voronoi100re',
            name='scn_name',
        ),
    ]
