# Generated by Django 3.2.18 on 2023-07-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0051_remove_ch4voronoi100re_scn_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ch4voronoi',
            name='scn_name',
        ),
    ]
