# Generated by Django 3.2.18 on 2023-07-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0052_remove_ch4voronoi_scn_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='h2voronoi',
            name='scn_name',
        ),
        migrations.RemoveField(
            model_name='h2voronoi100re',
            name='scn_name',
        ),
    ]
